Calculator
BezzB/Math-magician pull request #2
Opened 2023-05-10 12:14 UTC by BezzB

Delete all the boilerplate from Create React App (text, images, styles).
Create a new directory called components.
Inside components, create a new Calculator.js file.
In Calculator.js, create a React component that matches this design:
Calculator

Implement the design only (JSX and CSS)
Develop just the UI of the calculator; the math logic to make it work will be added in the next project.
Use functional components
Create at least 1 child component
Once the Calculator is ready, import it and use it in your top-level component: App.js
Test it in the browser; it should render without problems.

2023-05-10 12:33 UTC, julie-ify requested changes
## Hi @BezzB,

Good job so far!

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 12:33 UTC, julie-ify commented on src/component/Calculator.js
> +function App() {
- [ ] This component name should be Calculator as specified in the requirements. We already have an App component, there is no need creating another one.

- [ ] Kindly note that this Calculator component should have at least one child component. Kindly create that.

2023-05-10 12:33 UTC, julie-ify commented on src/App.js
> +function MainApp() {
- [ ] Kindly maintain the previous component name `App` which you had before.

2023-05-10 13:56 UTC, DuaneDave requested changes
Hi @BezzB 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ Correct naming convention for components


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 13:56 UTC, DuaneDave commented on src/component/Calculator.js
> +        <div className="operators">
As previously [mentioned](https://github.com/BezzB/Math-magician/pull/2#:~:text=Kindly%20note%20that%20this%20Calculator%20component%20should%20have%20at%20least%20one%20child%20component.%20Kindly%20create%20that.), the calculator component is expected to have one child component with in it, that is you should create a new file and import that file as a component inside of this file.

HINT: since the button is repeating, you can extract it as its own component and render it here like this <Button />

2023-05-10 15:20 UTC, frank1738 requested changes
Hi @BezzB , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

✅ Correct use of Gitflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 15:20 UTC, frank1738 commented on src/component/Calculator.js
> +        // eslint-disable-next-line react/button-has-type
- [ ] Kindly note that `operate.js` cannot be considered a component as it does not render any user interface. It contains a utility function that helps in performing calculations. As hinted previously, you can have a separate button component or create a different component containing the buttons

2023-05-11 11:56 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @BezzB,

✔️ Implementation of child component

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 11:57 UTC, merged